### ISSUE TITLE
Java agent fails to detect dependency - spring-security-oauth2-client.jar

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1342]
### Description
When running the click application mentioned in this [tutorial](https://spring.io/guides/tutorials/spring-boot-oauth2/) wired with latest java agent version, the environment settings do not display the spring-security-oauth2-client.jar despite being loaded as part of startup for this application. 

### Acceptance Criteria
Determine why the agent jar collector doesn't report this jar file and correct.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
N/A

**Comment by jtduffy** [comment]
Moving comments from closed Jira issue to here:
The agent ships with an [excludes file](https://github.com/newrelic/newrelic-java-agent/blob/main/newrelic-agent/src/main/resources/META-INF/excludes) which contains a list of regular expressions. If a class or package matches one of these regular expressions, it's excluded from being weaved.

All Spring Security related packages are excluded, per this in the exclude file:
```
# Instrumentation of Spring security classes breaks webapps
^org/springframework/security.* 
```

The agent will not report a jar file to the collector if everything in jar under consideration is excluded - which is why all Spring Security jars fail to appear on the environment/jar page in NR.

--------

A good place to start looking:
https://github.com/newrelic/newrelic-java-agent/blob/3062016206be7a87e7be9aa65507156d84913a59/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationContextManager.java#L150

Exclusions are managed in the InstrumentationContextManager.  need to decouple preventing weave from sending jars.

**Comment by jtduffy** [comment]
Currently, the jar collector functionality is implemented via the `ClassMatchVisitor` pattern. The problem with this approach is that the registered visitors aren't executed when a class is excluded from transformation.  In the case of certain jars (Spring Security for example), every single class in the jar is excluded, so the visitors are never executed, so the jar collector is never aware of the enclosing jar.

The solution is to refactor the jar collector logic so it's no longer registered as a `ClassMatchVisitor`.  In addition, the classes would be submitted to the jar collector, regardless of it's transformation/exclude status.


This stack trace shows the call sequence up to the `transform()` method, where a class is check for exclusion.
```
com.newrelic.agent.instrumentation.context.InstrumentationClassTransformer.transform(InstrumentationClassTransformer.java:70)
java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
java.base/java.lang.ClassLoader.defineClass1(Native Method)
java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
com.newrelic.agent.instrumentation.weaver.ClassWeaverService.createRetransformRunnable(ClassWeaverService.java:151)
com.newrelic.agent.instrumentation.context.InstrumentationContextManager.create(InstrumentationContextManager.java:193)
com.newrelic.agent.instrumentation.ClassTransformerServiceImpl.startClassTransformer(ClassTransformerServiceImpl.java:153)
com.newrelic.agent.instrumentation.ClassTransformerServiceImpl.doStart(ClassTransformerServiceImpl.java:117)
com.newrelic.agent.service.AbstractService.start(AbstractService.java:63)
com.newrelic.agent.service.ServiceManagerImpl.doStart(ServiceManagerImpl.java:218)
com.newrelic.agent.service.AbstractService.start(AbstractService.java:63)
com.newrelic.agent.Agent.continuePremain(Agent.java:173)
```
