### ISSUE TITLE
Newrelic Java agent instruments Jasper in such a way, that some JSP pages stop producing html and body tags

### ISSUE THREAD

**Issue by pavelsher** [newrelic/newrelic-java-agent#1409]
## Description
We have a suspicion that Newrelic Java agent with options 
browser_monitoring: 
  auto_instrument: true

enabled changes behavior of Jasper JSP compiler in such a way that certain JSPs stop emitting <html> and <body> tags.
This happens with fresh TeamCity 2023.05 installation (https://download.jetbrains.com/teamcity/TeamCity-2023.05.exe). If TeamCity is started with newrelic Java agent then it is unable to properly render login page, and since Java agent instruments Jasper code, incorrect JSP files are being stored on disk and compiled, thus making the entire TeamCity installation broken.

For us this is quite a critical problem. We've already got at least two customers who could not upgrade their TeamCity because of this issue.

## Steps to Reproduce
1. Download TeamCity for Windows: https://download.jetbrains.com/teamcity/TeamCity-2023.05.exe
2. Follow installation steps 
3. Before starting TeamCity add TEAMCITY_SERVER_OPTS environment variable with JVM argument which enables newrelic Java agent
4. Start TeamCity server and after some intialization steps observe messy pages 

## Additional details

TeamCity has an externalPage.tag. This tag clearly has html and body tags. However produced java file which is being put under the work/Catalina directory no longer has these tags. 

Newrelic java agent version: 7.4.1

**Comment by dekachiri** [comment]
I am experiencing the same problem in my environment.

tomcat: 9.0.82
Java: corretto 1.8.0_372.b07-1
jasper: bundled with tomcat
newrelic: java-agent 7.4.3

**Comment by jtduffy** [comment]
@pavelsher @dekachiri 
The issue you're seeing is a bug that was corrected in later versions of the agent - it was incorrectly searching for the `head` string, disregarding its location on the page.

However, with this bug corrected, the majority of JSPs in TeamCity will not be auto-instrumented with the NR browser agent. The reason is that we're expecting the `<html> <head>` tags to existing in the preprocessed JSP, and the TeamCity JSPs get their HTML generated as part of the various tags present in the JSP. See this [code snippet](https://github.com/newrelic/newrelic-java-agent/blob/4724f7f086a82d61872df8c95dd9a3af4538ad41/newrelic-agent/src/main/java/com/newrelic/agent/tracers/jasper/GeneratorVisitBodyTracerFactory.java#L43) for more info.

The alternative is for the end users to [manually add](https://docs.newrelic.com/docs/apm/agents/java-agent/instrumentation/instrument-browser-monitoring-java-agent-api/#manual_instrumentation) the header/footer JS snippet to the desired pages.
