### ISSUE TITLE
New Relic Agent JAR Contains 3 unpatched MEDIUM CVEs

### ISSUE THREAD

**Issue by Abdullah-Shahen** [newrelic/newrelic-java-agent#1580]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
> **WARNING**
> This is not really a Bug, but a Security related request. Please point me to the right process if this way is incorrect.

As a DevSecOps responsible in my Team, I have encountered the following CVEs during my latest security scans: 
| CVE|      Severity|  Package / Path|
|----------|:-------------:|------:|
| [CVE-2015-3192](https://avd.aquasec.com/nvd/cve-2015-3192) |  MEDIUM | ../newrelic.jar/newrelic-security-agent.jar/instrumentation-security/spring-web-1.0.jar:1 |
| [CVE-2013-6430](https://avd.aquasec.com/nvd/cve-2013-6430) |    MEDIUM |  ../newrelic.jar/newrelic-security-agent.jar/instrumentation-security/spring-web-1.0.jar:1 |
| [CVE-2013-6429](https://avd.aquasec.com/nvd/cve-2013-6429) | MEDIUM  |   ../newrelic.jar/newrelic-security-agent.jar/instrumentation-security/spring-web-1.0.jar:1 |

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
I expect New Relic to have internal Security Scans (Which I assume they do) and be able to address theses CVEs. 
The latest version for the agent should not have unpatched CVEs.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )
N/A

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )
If you scan the agent's jar with tools like Trivy, you will detect the CVEs

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible, including the running version of New Relic software, JVM vendor and version, framework versions, and any relevant configuration. )
We are running the agent inside a Docker Container alongside our App.jar

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )
N/A

**Comment by Abdullah-Shahen** [comment]
Added @Abdullah-Benomar-Shahen

**Comment by meiao** [comment]
@Abdullah-Shahen the jar you mention is not really the Spring framework jar, but the instrumentation module for the Spring framework.
The instrumentation module is named after the original artifact and may contain classes with the same name or similar to classes in the original artifact. These classes do not contain the code from the original, but code that is added to the original so that data can be sent to New Relic.

Check our documentation on this:
https://docs.newrelic.com/docs/apm/agents/java-agent/troubleshooting/java-agent-identified-with-security-vulnerabilities/

Note that the jar you mentioned is on the newrelic-security-agent.jar, and its instrumentation modules are located in:
https://github.com/newrelic/csec-java-agent/tree/main/instrumentation-security

**Comment by Abdullah-Shahen** [comment]
Thanks for the rapid response, @meiao
