### ISSUE TITLE
High memory consumption and unexpected behavior relating to @Trace annotation in Spring / Kafka.

### ISSUE THREAD

**Issue by JesseLaughlin** [newrelic/newrelic-java-agent#1590]
## Description
Customer has `@Trace(dispatcher=true)` annotation on their Kafka `onMessage()` method.  This annotation worked as expected in agent v7.9.0.  However, when he upgraded to v7.10.0, the APM Transaction generated by this annotation stopped reporting.  He then tried adding a `metricName` to the annotation, and got the Transaction to report again.  However, he immediately saw a sharp increase in heap memory consumption, that climbed steadily until eventually hitting an OOM condition.  This happened even when doubling the heap memory on the JVM.

## Expected Behavior
Rolling back to v7.9.0 did not encounter the high memory condition, with or without the `metricName`.  These were the only changes made in this environment at the time.  We would expect `@Trace` to work the same in both agent versions.  We also would not expect setting a `metricName` explicitly to change the behavior.  The `metricName` passed was a static string, not a variable, so the number of Transactions reported in both conditions (with or without `metricName`) should be 1.  

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
We gathered logs, and interestingly, in the condition where `metricName` was set (running the latest Java agent), we say a large number of requests to rename the same Transaction based on the `@Trace` annotation.  More than 300 separate attempts to set the Transaction name to the same value, suggesting that the `onMessage()` method was somehow called many times in a single request.

When we removed the `metricName`, we saw no Transaction data reported.  No attempts to start or rename a request when `onMessage()` was called.  The agent still wrapped the `onMessage()` method, but behaved as if that method was never called at runtime.

## Steps to Reproduce
This customer was kind enough to create a stripped-down version of their application that reproduces the issue:
https://github.com/PublicRelay/repro-kafka-newrelic-oom

...note that they first attempted to create a new Spring Boot test app and reproduce the problem from there, but they did not encounter the same behavior.  The agent and `@Trace` annotation both performed as expected.  He then tried working backwards from the original application, removing any sensitive code but leaving the method call structure intact.  This repro attempt was successful, and the link above is the result.  This suggests that we're hitting some sort of edge case in this application that isn't generally encountered.

**Comment by obenkenobi** [comment]
When I attempted to run the repro, the memory maxed out at 1.44 GB near startup but lowered to 727MB and stayed consistent there. I believe the memory consumption comes from the fact the customer is creating a trace per every kafka message it consumes. Usually Kafka consumer apps are high throughput and we wouldn't encourage creating a tracer per message due to the overhead involved in such an act. However based on the repro, the memory does plateau so the question here is how big the spike is in the beginning. It may also be useful to instead only allow a smaller amount of messages be traced (i.e. sampled out) to account for such an overhead. We do provide Kafka metrics to measure consumer throughput which would compensate for this.

**Comment by obenkenobi** [comment]
Since I failed to replicate the OOM with the working docker examples, I believe there needs to be restrictions on the environment needed to produce such an error (i.e. limitations on available memory in a docker container).

**Comment by obenkenobi** [comment]
@JesseLaughlin

So looking into the OOM issue, we discovered some important info that can cause an OOM based on the provided repro.

First is that we see the `init` method in DispatcherServlet generated a transaction with 1500 traces.

![image](https://github.com/newrelic/newrelic-java-agent/assets/46640034/53493cb5-964a-4c6e-80c9-99abbae11c3a)

We see inside the DispatcherServlet transaction, we see that the `onMessage` trace is created inside and there are child `onMessage` calls. Looking inside the stack trace, we see the `onMessage` calls are created from `CompletableFutures`.

```
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at com.publicrelay.nrtest.kafka.listener.PrKafkaMessageListener.onMessage(PrKafkaMessageListener.java:41)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at com.publicrelay.nrtest.kafka.listener.PrKafkaMessageListener.onMessage(PrKafkaMessageListener.java:15)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2883)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2854)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.lambda$doInvokeRecordListener$57(KafkaMessageListenerContainer.java:2772)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at io.micrometer.observation.Observation.observe(Observation.java:562)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:2770)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:2622)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:2508)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:2150)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1505)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1469)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1344)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
repro-kafka-newrelic-oom-newrelic-oom-repro-1  |        at java.base/java.lang.Thread.run(Thread.java:840)

```


My conclusion here is that Spring's DispatcherServlet `init` method creates a transaction and CompletableFuture(s) that calls the `onMessage` method call and creates a trace. Because of our CompletableFuture instrumentation, this causes the `init` method to spawn a token and link it within a parent method call before `onMessage` is hit. The conclusion here is it is our `CompletableFuture` instrumentation that is the culprit.

Disabling the `CompletableFuture` instrumentation fixes the issue. 

So to disable the instrumentation based on our [config docs](https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/#Class_Transformer), add the following inside the `class_transformer` stanza in `newrelic.yml`:

```yml
    com.newrelic.instrumentation.java.completable-future-jdk8u40:
      enabled: false
```

**Comment by obenkenobi** [comment]
Issue closed because we have troubleshooting recommendations for the customer
