### ISSUE TITLE
Consider updating the agent installation docs for Resin server to call out issues running on Windows with Java 9+

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#1714]
The current installation docs for resin document how to start the server with the Java agent attached on Java 9+ when using an OSX/Linux system. However, when trying to run on a Windows server all of the installation methods cause resin to fail to startup with a `java.lang.NoClassDefFoundError: java/sql/SQLException`.

https://docs.newrelic.com/docs/apm/agents/java-agent/additional-installation/include-java-agent-jvm-argument/#Installing_on_Resin

If we cannot determine a fix to get resin to run with the Java agent on Windows then we should consider updating the doc to call out that lack of support.

Some relevant details about the environment where these issues were observed:

- Java agent 7+
- Java 9+
- Resin Pro 4.0.66
- Windows server 2019

**Comment by meiao** [comment]
It looks like Resin uses a different system class loader that is not overridden by the regular configuration.
This class loader does not seem to work too well with modules when running on Windows.

It is not simply a timing issue because dynamic attach does not work.
Adding module configuration to the jvm args does not seem to work either.
Instrumenting this class loader, or its config, won't work because the exception happens before the weaver is running.
The jar loading hack used to load the agent-bridge-datastore won't work without a lot of refactor because the class being loaded that throws the exception is in newrelic-agent.

Resin installation doc has been updated with a note that the agent wont work in this scenario.
