### ISSUE TITLE
Add support for mssql-jdbc 12.7.0

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#1844]
### Description
Our instrumentation `jdbc-sqlserver` is not compatible with the new version of mssql-jdbc.

Verifier error:
```
   > Verification FAILED. Instrumentation module jdbc-sqlserver-1.0.jar SHOULD HAVE applied to com.microsoft.sqlserver:mssql-jdbc:12.7.0 and did not. You may need to adjust the range "com.microsoft.sqlserver:mssql-jdbc:[0,)".
     Verifier output:
     Creating user classloader with custom classpath:
     WeaveViolation{type=MISSING_ORIGINAL_BYTECODE, clazz=com/microsoft/sqlserver/jdbc/SQLServerDriver}
     WeaveViolation{type=MISSING_ORIGINAL_BYTECODE, clazz=com/microsoft/sqlserver/jdbc/SQLServerDataSource}
```

**Comment by jbedell-newrelic** [comment]
This may not be a complete re-work.  As of today 12.7.0 has not been officially released.  The verify failed on a preview release that appeared to possibly just be packaged oddly.

**Comment by deleonenriqueta** [comment]
After looking into the WeaveViolations caused by `mssql-jdbc-12.7.0`, I found that this version was only a pre-release. There is a subsequent pre-release (12.7.1) and a fully supported release (12.8.0), both of which don't trigger these WeaveViolations. To avoid false alarms in the future, I've excluded `mssql-jdbc-12.7.0` from being run through instrumentation verification.
