### ISSUE TITLE
Environment variable should take precedence over System Property

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-java-agent#330]
## Description

Hello,
Per https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file/#config-options-precedence and https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file/#Environment_Variables it is stated that environment variables take precedence over system properties. However, we are not seeing that work as expected with the agent_enabled setting, where we have the env var NEW_RELIC_AGENT_ENABLED=true but -Dnewrelic.config.agent_enabled=false, and the agent outputs “New Relic Agent is disabled by -Dnewrelic.config.agent_enabled system property.”

Looking at the agent code at https://github.com/newrelic/newrelic-java-agent/blob/3735fb1b6cf54155adb589376d4340e507ecbadd/newrelic-agent/src/main/java/com/newrelic/bootstrap/BootstrapAgent.java#L101-L113, the logic is doing the opposite of what the documentation specifies.

Can this either be corrected in the agent code, or update the docs to indicate this exception to the rule (since it seems agent_enabled is treated differently)? 

## Expected Behavior

When env var NEW_RELIC_AGENT_ENABLED=true and -Dnewrelic.config.agent_enabled=false, 
the agent should respect the environment variable and start.

## Steps to Reproduce
Setenv var NEW_RELIC_AGENT_ENABLED=true
Set system property -Dnewrelic.config.agent_enabled=false

The agent will not start but it should.

**Comment by Stephan202** [comment]
IMHO the code is fine; I'd update the documentation instead. Generally more specific settings should override more general settings. System properties are more specific than environment variables, since the former are per-JVM, while an environment can contain multiple JVMs.

Afaik most software follows this rule. Examples include [Spring](https://docs.spring.io/spring-boot/docs/2.5.1/reference/html/features.html#features.external-config) and the [AWS SDK](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.html).

**Comment by jasonjkeller** [comment]
I haven't looked closely at this issue but most agent config options follow this precedence (highest on top). 

<img width="386" alt="Screen Shot 2021-09-02 at 9 52 43 AM" src="https://docs.newrelic.com/static/60ca967eab99ca225186310913ae2de6/8c557/java-config-cascade.png">

**Comment by kford-newrelic** [comment]
Not selected for the agent roadmap. Will consider a change in the docs instead.
