### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#417]
Investigate what documentation needs to be updated to account for the new DT defaults and config as well as calling out that CAT is deprecated. Submit PRs to the doc site with any required doc changes. We'll want to time these with the next agent release.

**Comment by meiao** [comment]
[Preview PR](https://github.com/meiao/docs-website/pull/1)

Pages changed:
- [Java agent API: Instrumenting example app for external datastore calls and CAT](https://docs.newrelic.com/docs/agents/java-agent/api-guides/java-agent-api-instrumenting-example-app-external-datastore-calls-cat/)
-- changed file name `java-agent-api-...-calls-cat` -> `java-agent-api-...-calls-dt`, with old page redirecting to new
-- changed `cross application tracing` to `distributed tracing`
-- example code works both for CAT and DT

- [Java agent config file template](https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-config-file-template/)
-- copied template from repo

- [Messaging framework instrumentation](https://docs.newrelic.com/docs/agents/java-agent/custom-instrumentation/messaging-framework-instrumentation/)
-- changed example code to use non deprecated methods

- [Java agent: Instrument Kafka message queues](https://docs.newrelic.com/docs/agents/java-agent/instrumentation/java-agent-instrument-kafka-message-queues/)
-- changed wording to instead of enabling DT, to check if DT is enabled

**Comment by jasonjkeller** [comment]
@meiao I didn't see this in your PR (I might have just overlooked it), but we'll also want to add the [new config for span events](https://github.com/newrelic/newrelic-java-agent/issues/414) to the [agent config doc](https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file/#span-events):

```
  span_events:
    max_samples_stored: 2000 
```

Default is currently set to `2000`
