### ISSUE TITLE
OOM errors and memory leak caused by caffeine cache and java8

### ISSUE THREAD

**Issue by T00fy** [newrelic/newrelic-java-agent#623]
We recently upgraded the agent in our java8 application from 7.1.1 to 7.4.2 due to the log4shell exploit. We've noticed since then that very randomly and intermittently a single container can encounter a memory leak that eventually causes an OOM exception. Initial troubleshooting lead me to this issue which looks very similar to the issue I am encountering https://github.com/newrelic/newrelic-java-agent/issues/558

## Description
We deploy multiple docker containers, and randomly after a set amount of time one of these will eventually hit some condition which causes the GC to not clean up unused resources. We have been able to capture a heap dump at the time of this memory leak and the suspected issue using MAT is com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.WS. For comparison, in containers not experiencing a memory leak or running on an older version of NR agent we do not see this in the report.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
I have a large heap dump file which for obvious reasons I am not going to post in here, but if you could point me to any relevant details to provide which may be of help I would be happy to oblige.

So far I have just been using MAT to explore the dump file and there are a LOT of objects being instantiated in the caffeine cache with a WeakKeyReference

<img width="628" alt="image" src="https://user-images.githubusercontent.com/12580207/147425161-07276911-2453-4250-9d0c-dbd1bf9ee585.png">

<img width="773" alt="image" src="https://user-images.githubusercontent.com/12580207/147425204-3856e7e4-97e4-4081-8ff7-75c9d4a0ff25.png">

<img width="692" alt="image" src="https://user-images.githubusercontent.com/12580207/147425260-5e9f8c0c-f9cd-4dd3-9249-de9afba5b4ad.png">

<img width="795" alt="image" src="https://user-images.githubusercontent.com/12580207/147425534-d08ad250-2ae6-472b-811d-fdfac581c886.png">

## Your Environment
Newrelic agent 7.4.2
openJDK 1.8.0_292-8u292

## Additional context
Looks very similar to https://github.com/newrelic/newrelic-java-agent/issues/558 but I am running java8 and not upgrading to java 17 or 11. There was a lot of discussion in that issue about a bug in the JDK but I'm not convinced that is the issue unless it is also affecting java8 somehow.

**Comment by ben-manes** [comment]
I was unable to reproduce this in a stress test with 8u292 and `-XX:ActiveProcessorCount=1`. If you can determine a bug in the caching library then please open an issue there.

One possibility is if your application has blocked all `ForkJoinPool.commonPool()` threads so that no other work may be performed on this JVM-wide threadpool (e.g. created by `CompletableFuture.supplyAsync`). This would halt the maintenance work to evict from the cache as the task is scheduled but cannot be run. In the latest version Caffeine enables its mitigation path to include reference caching, and the next newrelic path switches to a same-thread executor. You could use jstack to check if the pool is being used by long-running or hung tasks.

**Comment by T00fy** [comment]
Hey @ben-manes thanks for your reply. 

We do have some code on a listener that runs
`CompletableFuture.runAsync(() -> blah;` a lot. Could this be a culprit for blocking the caffiene cache from evicting?

**Comment by ben-manes** [comment]
Yes, if those are long-running operations that starve out other usages. If that is the case, then consider supplying a dedicated executor to `runAsync`.

The FJP common pool is an odd beast. The thread pool is designed for many short, cpu-bound tasks and limits the number of threads close to the number of cpu cores. This pool does not tolerate blocking very well, but tries to unstick itself by creating compensating workers if blocking is detected. For more long-running or I/O bounded work a `ThreadPoolExecutor` is ideal, e.g. via `Executors.newCachedThreadPool()`. The question is why FJP was chosen the shared pool for default use by `CompletableFuture`, which is a poor match. All of this will be resolved when virtual threads land (Loom) because it will be the ideal pool for that workload pattern (bursty work piles with async I/O).

Caffeine's own logic doesn't need async, but it makes callbacks to user supplied code. Any unknown foreign code could be expensive, so performing that on a caller thread might have undesirable user-facing latency. Therefore by default we defer onto an executor, using commonPool() since that is the JVM's default. In most cases the cache handles when the executor discards or otherwise never runs the task, but this case for reference caching was missed. The fix still points to an application problem that we compensate for, so you'll probably want to resolve the root issue to correct other usages affected by starvation.

**Comment by kford-newrelic** [comment]
@T00fy thanks for raising this topic - hopefully the response from @ben-manes helps to clarify the issue you're seeing.
