### ISSUE TITLE
[Spike] Jakarta renaming 

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#689]
Need to investigate impact, scope and effort to adapt for Jakarta namespaces being renamed.

Aha! Link: https://newrelic.aha.io/features/JAVA-361

**Comment by kford-newrelic** [comment]
Comment added by Evan Haxton in Aha! - [View](https://newrelic.aha.io/comments/7081299342281488786)

Related FR: [ JAVA-I-1133](https://newrelic.aha.io/ideas/ideas/JAVA-I-1133?reference-class=Ideas%3A%3AIdea)  
  
  
Customer: Opentext  
TC10/Jakarta EE support has been driven by OpenText's 90 day release cycle initiative. The next release cycle begins April 1st and all services captured in this [diagram](https://docs.google.com/presentation/d/1I-23wHa4FMZqj4QpddYCVTxqHVK6cqTM/edit#slide=id.g107340e65d8_0_19) will be deployed on TC10 over the course of the month. There are approximately 5000 customers across all of these services and OT is nervous about potential customer impact resulting from observability blind spots.  
  
  
Customer is willing to support a BETA on this initiative but is looking for a more definitive timeline  
  
  
cc [@Keith Morris](https://newrelic.aha.io/users/6745610487640350571) [@Victor Restrepo](https://newrelic.aha.io/users/6424387625008821937)

**Comment by jasonjkeller** [comment]
Spike has been completed. Findings are in this doc: https://docs.google.com/document/d/1nGL-pgurtIZ2okxdLOVr6MrpGxp6Fl4LQcEgWTfTkbA/edit#

It will be easy to create stories when we are ready to take on this work but because there will be many of them I've held off until we know for certain whether or not they should be in Github or Jira.
