### ISSUE TITLE
Unsupported class file major version 62

### ISSUE THREAD

**Issue by jdezego** [newrelic/newrelic-java-agent#821]
When following the build instruction in the readme file we see this error after running `gradlew clean jar --parallel`

General error during semantic analysis: Unsupported class file major version 62

**Comment by meiao** [comment]
Did you try to compile the agent with Java 18?
The agent must be compiled with Java 8 and a module requires 11.

**Comment by jdezego** [comment]
Thanks @meiao . Yes, openjdk 8 is installed and JAVA_HOME points to it. Are you saying Java 11 is also required? If so would I just install it and add a jdk11= line in the gradle config file? I don't see that mentioned in the readme. I see a reference to jdk9 but that seems to be optional.

**Comment by meiao** [comment]
You don't need to install it. Gradle will download a Java 11 if it cannot find one in your machine.
You'd need to configure it to run tests with Java 11.

The class file major version 62, leads me to believe that it ran with Java 18.

I did run with 18 and got the same error, with this stack trace
```
> startup failed:
  General error during semantic analysis: Unsupported class file major version 62

  java.lang.IllegalArgumentException: Unsupported class file major version 62
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
```

Which is a Gradle error, likely because the version of Gradle we are using does not run with 18.
Does `java -version` returns 1.8?

**Comment by jdezego** [comment]
Thank you so much. I have a mess of versions laying around. I'll clean that
all up, but could you link me to the specific jdk I need to use? I want to
be sure I get it right.

**Comment by meiao** [comment]
Any 8 should work. We use Temurim from [Adoptium](https://adoptium.net/temurin/releases).
