### ISSUE TITLE
Akka Transaction Naming

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#864]
![Screen Shot 2022-05-26 at 1 16 12 PM](https://user-images.githubusercontent.com/653013/170540569-3fc21310-145b-4c88-b03c-de1f1263864a.png)

<img width="413" alt="Screen Shot 2022-05-26 at 1 13 46 PM" src="https://user-images.githubusercontent.com/653013/170540313-13071763-ee72-4ebd-bf1a-90beac04f1c6.png">

The transaction naming for this version of akka seems to be incorrect or broken.  We need to investigate and see how we might need to fix it.

**Comment by meiao** [comment]
This is caused by the Mongo (reactive?) drivers that use Akka under the hood.
I don't believe there is anything wrong with the Akka instrumentation, but we should prevent this actor from being instrumented, or if possible, mark an earlier method as a leaf so this thread naming does not overwrite the name already in the transaction.

**Comment by kford-newrelic** [comment]
Migrated to Jira (https://issues.newrelic.com/browse/NR-25451).
