### ISSUE TITLE
NewRelic 7.9.0: java.lang.NoClassDefFoundError: com.newrelic.agent.bridge.datastore.RecordSql

### ISSUE THREAD

**Issue by gillesbergerp** [newrelic/newrelic-java-agent#979]
### Description
We are facing an issue with the NewRelic java agent version 7.9.0 on JDK17: `java.lang.NoClassDefFoundError: com.newrelic.agent.bridge.datastore.RecordSql`

### Your Environment
- openjdk version "17.0.4" 2022-07-19
- Ubuntu
- NewRelic Agent 7.9.0

**Comment by kford-newrelic** [comment]
@gillesbergerp did you have a working installation before that you modified/upgraded or is this a new installation?

What JDK distribution are you using? What happens if you use an earlier version (for troubleshooting purposes) - like Java 16?

Troubleshooting this may require a more in-depth focus than is typical for GitHub issues - you might want to look at our other [Global Technical Support](https://docs.newrelic.com/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings/) offerings.

**Comment by kford-newrelic** [comment]
@gillesbergerp Sorry, just noticed that you closed this issue - were you able to figure out the problem?

**Comment by kford-newrelic** [comment]
Ah, gotcha. Thanks for the update.

We're working on #841 , so we're hopeful that soon our agent will be working with Semeru...
